version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c ./entry_point.sh
    container_name: r5_service
    env_file:
      - .env
    ports:
      - ${PUBLISHED_PORT}:${TARGET_PORT}
    volumes:
      - .:/app
